services:
  mariadb1:
    image: mariadb:latest
    container_name: mariadb1
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: demo
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
      - ./mariadb-server/primary/primary.cnf:/etc/mysql/mariadb.conf.d/primary.cnf
      - ./mariadb-server/primary/primary.sql:/docker-entrypoint-initdb.d/primary.sql

  mariadb2:
    image: mariadb:latest
    container_name: mariadb2
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_MASTER_HOST: mariadb1
      MARIADB_REPLICATION_USER: repl_user
      MARIADB_REPLICATION_PASSWORD: repl_password
    volumes:
      - ./mariadb-server/replica/replica1.cnf:/etc/mysql/mariadb.conf.d/replica1.cnf

  mariadb3:
    image: mariadb:latest
    container_name: mariadb3
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_MASTER_HOST: mariadb1
      MARIADB_REPLICATION_USER: repl_user
      MARIADB_REPLICATION_PASSWORD: repl_password
    volumes:
      - ./mariadb-server/replica/replica2.cnf:/etc/mysql/mariadb.conf.d/replica2.cnf

  maxscale1:
    image: mariadb/maxscale:24.02
    container_name: maxscale1
    volumes:
      - ./maxscale-proxy/maxscale.cnf:/etc/maxscale.cnf
    ports:
      - "4001:4000"
      - "8981:8989"
    depends_on:
      - mariadb1
      - mariadb2
      - mariadb3

  maxscale2:
    image: mariadb/maxscale:24.02
    container_name: maxscale2
    volumes:
      - ./maxscale-proxy/maxscale.cnf:/etc/maxscale.cnf
    ports:
      - "4002:4000"
      - "8982:8989"
    depends_on:
      - mariadb1
      - mariadb2
      - mariadb3

  maxscale3:
    image: mariadb/maxscale:24.02
    container_name: maxscale3
    volumes:
      - ./maxscale-proxy/maxscale.cnf:/etc/maxscale.cnf
    ports:
      - "4003:4000"
      - "8983:8989"
    depends_on:
      - mariadb1
      - mariadb2
      - mariadb3

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8989:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - maxscale1
      - maxscale2
      - maxscale3
